# Generated by Django 2.1.2 on 2018-11-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_administration', '0002_customuser_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('edit_user', 'Edit user'), ('delete_user', 'Delete user'))},
        ),
    ]
