# Generated by Django 2.1.2 on 2018-11-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_administration', '0003_auto_20181104_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
    ]
