# Generated by Django 2.1.2 on 2018-11-11 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_administration', '0004_remove_customuser_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Enter a valid first name.This value may contain only letters.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='iban',
            field=models.CharField(max_length=34, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[0-9]{2}[a-zA-z0-9]{4}[0-9]{7}([a-zA-z0-9]?){0,19}$', 'Enter a valid IBAN. It should start with country code and may contain only letters, numbers.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-z]+$', 'Enter a valid last name.This value may contain only letters.')]),
        ),
    ]
